name: Test

on: push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        version:
          - 4.3.5
          - 4.3.6
          - 4.3.7
          - 4.3.8
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Test
        run: |
          export VERSION=${{ matrix.version }}
          ./gradlew wrapper
          ./gradlew :app:processFooBarHelloWorldDebugGoogleServices
